files:
  - source: /custom_components/dreame_vacuum/translations/en.json
    translation: /custom_components/dreame_vacuum/translations/%two_letters_code%.json
  - name: crowdin-action
    uses: crowdin/github-action@v2.1.1
